apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.name | quote }}
    app.kubernetes.io/component: {{ .Values.name | quote }}
    app.kubernetes.io/instance: {{ .Values.name | quote }}
    app.kubernetes.io/name: {{ .Values.name | quote }}
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ .Values.name | quote }}
    weight: 100
  wildcardPolicy: None
