apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name | quote }}
    app.kubernetes.io/component: {{ .Values.name | quote }}
    app.kubernetes.io/instance: {{ .Values.name | quote }}
    app.kubernetes.io/name: {{ .Values.name | quote }}
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: {{ .Values.name | quote }}
  sessionAffinity: None
  type: ClusterIP
