---
apiVersion: v1
kind: Namespace
metadata:
  name: testapp-ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testapp-ci-pipeline-sa
  namespace: testapp-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: testapp-ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testapp-ci-pipeline-sa
  namespace: testapp-qa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: testapp-ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testapp-ci-pipeline-sa
  namespace: testapp-pr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: testapp-ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testapp-ci-pipeline-sa
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: testapp-ci
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testapp-ci-source
  namespace: testapp-ci
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testapp-ci-helm
  namespace: testapp-ci
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    tekton.dev/git-0: https://gitea-server-gitea.apps-crc.testing
type: kubernetes.io/basic-auth
stringData:
  username: jfblaine
  password: asdfasdf
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-testapp
  namespace: testapp-ci
spec:
  host: el-testapp-testapp-ci.apps-crc.testing
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-testapp
    weight: 100
  wildcardPolicy: None
